#!/usr/bin/env python3
"""Generate C++ HalfKAv2_hm lookup tables from Python reference."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "nnue_training"))

import features.half_ka_v2_hm as h  # noqa: E402

OUT = ROOT / "cpp" / "inc" / "xqwl_halfka_tables.inc"


def bb_to_u128(squares: frozenset[int]) -> tuple[int, int]:
    lo = hi = 0
    for sq in squares:
        if sq < 64:
            lo |= 1 << sq
        else:
            hi |= 1 << (sq - 64)
    return lo, hi


def main() -> None:
    h._ensure_psq_offsets()
    lines: list[str] = [
        "// Auto-generated by scripts/generate_halfka_cpp_tables.py — do not edit.",
        "#ifndef XQWL_HALFKA_TABLES_INC",
        "#define XQWL_HALFKA_TABLES_INC",
        "",
        "namespace xqwl_halfka {",
        "",
        f"constexpr int kPsNb = {h.PS_NB};",
        f"constexpr int kAttackBucketNb = {h.ATTACK_BUCKET_NB};",
        f"constexpr int kFeatures = {h.N_FEATURES};",
        f"constexpr int kMaxActive = 32;",
        "",
    ]

    lines.append("constexpr std::uint64_t kBalanceEncoding = 0xA4A92A74E989D3A7ULL;")
    lines.append("")

    lines.append("constexpr std::uint8_t kIndexMap[2][2][90] = {")
    for m in (0, 1):
        lines.append("  {")
        for r in (0, 1):
            row = ", ".join(str(h.INDEX_MAP[m][r][sq]) for sq in range(90))
            lines.append(f"    {{ {row} }},")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    lines.append("constexpr std::uint8_t kKingBucket[90][90][2] = {")
    for ksq in range(90):
        lines.append("  {")
        for oksq in range(90):
            b0 = h.KING_BUCKETS[ksq][oksq][0][0]
            mir = int(h.KING_BUCKETS[ksq][oksq][0][1])
            b1 = h.KING_BUCKETS[ksq][oksq][1][0]
            mir1 = int(h.KING_BUCKETS[ksq][oksq][1][1])
            # store bucket in low 7 bits, mirror in bit 7; midm=0 and midm=1 rows
            lines.append(f"    {{ {b0 | (mir << 7)}, {b1 | (mir1 << 7)} }},")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    lines.append("constexpr std::uint8_t kAttackBucket[3][3][3] = {")
    for rook in range(3):
        lines.append("  {")
        for knight in range(3):
            row = ", ".join(str(h.ATTACK_BUCKET[rook][knight][cannon]) for cannon in range(3))
            lines.append(f"    {{ {row} }},")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    lines.append("constexpr std::int16_t kPsqOffsets[16][90] = {")
    for pc in range(16):
        row = ", ".join(str(h.PSQ_OFFSETS[pc][sq]) if sq in h.VALID_BB[pc] else "-1" for sq in range(90))
        lines.append(f"  {{ {row} }},")
    lines.append("};")
    lines.append("")

    lines.append("constexpr std::uint64_t kMidMirrorEncoding[16][90] = {")
    for pc in range(16):
        row = ", ".join(f"0x{h.MID_MIRROR_ENCODING[pc][sq]:016X}ULL" for sq in range(90))
        lines.append(f"  {{ {row} }},")
    lines.append("};")
    lines.append("")

    lines.append("constexpr struct { std::uint64_t lo; std::uint64_t hi; } kValidBB[16] = {")
    for pc in range(16):
        lo, hi = bb_to_u128(h.VALID_BB[pc])
        lines.append(f"  {{ 0x{lo:016X}ULL, 0x{hi:016X}ULL }},")
    lines.append("};")
    lines.append("")

    lines.append("} // namespace xqwl_halfka")
    lines.append("")
    lines.append("#endif // XQWL_HALFKA_TABLES_INC")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size // 1024} KiB)")


if __name__ == "__main__":
    main()
